export const PICKUP_POINTS = [
  'Bengaluru Airport (KIA)',
  'Bus Station (Majestic)',
  'Railway Station YPR',
  'Railway Station BLR',
  'Indiranagar',
  'Koramangala',
  'Whitefield',
  'Electronic City',
  'Marathahalli',
  'Bellandur',
  'Sarjapur Road',
  'MG Road',
  'Brigade Road',
  'Commercial Street',
  'UB City',
  'Banaswadi',
  'Yelahanka',
  'Ramamurthy Nagar',
  'Gottigere',
  'Bannerghatta Road',
  'Jayanagar',
  'Basavanagudi',
  'Silk Board Junction',
  'Trinity Junction',
  'Vijayanagar'
];

export const DESTINATIONS = [
  'Bengaluru Airport (KIA)',
  'Bus Station (Majestic)',
  'Railway Station YPR',
  'Railway Station BLR',
  'Indiranagar',
  'Koramangala',
  'Whitefield',
  'Electronic City',
  'Marathahalli',
  'Bellandur',
  'Sarjapur Road',
  'MG Road',
  'Brigade Road',
  'Commercial Street',
  'UB City',
  'Banaswadi',
  'Yelahanka',
  'Ramamurthy Nagar',
  'Gottigere',
  'Bannerghatta Road',
  'Jayanagar',
  'Basavanagudi',
  'Silk Board Junction',
  'Trinity Junction',
  'Vijayanagar'
];
