export const PICKUP_POINTS = [
  'Bengaluru Airport',
  'Bus Station',
  'Railway Station',
  'Indiranagar',
  'Koramangala',
  'Whitefield',
  'Electronic City',
  'Marathahalli',
  'Bellandur',
  'Sarjapur Road',
  'MG Road',
  'Brigade Road',
  'Commercial Street',
  'UB City',
  'Banaswadi',
  'Yelahanka',
  'Ramamurthy Nagar',
  'Gottigere',
  'Bannerghatta Road',
  'Jayanagar',
  'Basavanagudi',
  'Silk Board Junction',
  'Trinity Junction',
  'Vijayanagar'
];

export const DESTINATIONS = [
  'Bengaluru Airport',
  'Bus Station',
  'Railway Station',
  'Indiranagar',
  'Koramangala',
  'Whitefield',
  'Electronic City',
  'Marathahalli',
  'Bellandur',
  'Sarjapur Road',
  'MG Road',
  'Brigade Road',
  'Commercial Street',
  'UB City',
  'Banaswadi',
  'Yelahanka',
  'Ramamurthy Nagar',
  'Gottigere',
  'Bannerghatta RD',
  'Jayanagar',
  'Basavanagudi',
  'Silk Board',
  'Trinity Junction',
  'Vijayanagar'
];
